version: '3.7'

services:
    salaries:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./app/.env.dev
        depends_on: 
            - salaries-db
    salaries-db:
        image: postgres:12-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=salaries
            - POSTGRES_PASSWORD=salaries
            - POSTGRES_DB=salaries_dev

volumes: 
    postgres_data:
