# Generated by Django 3.0.6 on 2020-05-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entry', models.CharField(max_length=14)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salaries.Payee'),
            preserve_default=False,
        ),
    ]
